version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: pipeline_script/ApplicationStart.sh
      runas: root
  ApplicationStop: 
    - localtion: pipeline_script/ApplicationStop.sh
      runas: root
