version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: pipeline_script/ApplicationStart.sh
      runas: linux
  ApplicationStop: 
    - localtion: pipeline_script/ApplicationStop.sh
      runas: linux

#canedio